### ISSUE TITLE
GetTX() type not correct

### ISSUE THREAD

**Issue by paulh002** [WA2FZW/An-FT-891-CAT-Control-Emulator-Library-by-WA2FZW#1]
The type of the function GetTX() is declared bool, I think it should be uint8_t because the value of radiostatus.TX has three states TX_OFF, TX_CAT, TX_MAN. If the status is TX_MAN the function GetTX() will return TX_CAT instead.

**Comment by WA2FZW** [comment]
Those three states are defined in the header file but not otherwise used. The real FT-891 uses those states (as I recall without looking), however, in the applications that I’ve used this library, I just care about the TX/RX state but not what caused the transition.
 
There are most likely a number of other things that would need to be changed as well.
 
John
WA2FZW

**Comment by paulh002** [comment]
It took me a while to figure out, but in the code  I use SetTX(TX_MAN), but if I query using GetTX() I got TX_CAT.  I changed it in my library. So now the issue is solved (for me). Other than that I like the solution and have it integrated in my, yes also, yet an other vfo :).

**Comment by WA2FZW** [comment]
Paul, upon further investigation, I see that in my NJAD VFO <https://github.com/WA2FZW/It-s-Not-Just-Another-Digital-VFO-by-WA2FZW-VK3PE-and-G3ZQC>  I did actually differentiate between “TX_CAT” and “TX_MAN” (Lines 1415 and following in the .ino file <https://github.com/WA2FZW/It-s-Not-Just-Another-Digital-VFO-by-WA2FZW-VK3PE-and-G3ZQC/blob/Version-1.1/NJAD_VFO_V1.1/NJAD_VFO_V1.1.ino> ), so I’ll make your change to the official copy of the library. 
 
Thanks!
 
John
WA2FZW

**Comment by WA2FZW** [comment]
Will shortly make Paul's change to the GetTX function.
